version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
        environment:
          VCD_TEST_CONFIG_FILE: ./tests/config.yml
          XDG_CACHE_HOME: ~/.cache
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install .
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            sed -i "s/HOST/$VCD_HOST/" tests/config.yml
            sed -i "s/USERNAME/$VCD_USERNAME/" tests/config.yml
            sed -i "s/PASSWORD/$VCD_PASSWORD/" tests/config.yml
            python -m unittest tests/vcd_login.py
      - run:
          name: Run build
          command: python setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: build-workspace
          paths:
            - dist

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - attach_workspace:
          at: ./repo
      - run:
          name: Install dependencies
          command: |
            sudo pip install twine
            twine upload dist/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
