version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
        environment:
          VCD_TEST_CONFIG_FILE: ./tests/config.yml
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install .
      - save_cache:
          paths:
            - /root/.cache/pip
          key: pip-packages-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            sed -i "s/HOST/$VCD_HOST/" tests/config.yml
            sed -i "s/USERNAME/$VCD_USERNAME/" tests/config.yml
            sed -i "s/PASSWORD/$VCD_PASSWORD/" tests/config.yml
            python -m unittest tests/vcd_login.py
      - run:
          name: Run build
          command: python setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy package
          command: |
            sudo pip install twine
            twine upload --skip-existing dist/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
